import type ts from "typescript";

import { exportFromBarrel, exportTypeStarFrom } from "../../ast/ts-build.js";
import { definePluginConfig } from "../../plugin.js";

import { defaultConfig } from "./config.js";
import type { IndexBarrelConfig, IndexBarrelResolvedConfig } from "./types.js";

const HEADER =
  "// AUTO-GENERATED by @ir-kit/asyncapi-typescript — do not hand-edit.";

/**
 * Barrel re-export of every other plugin's output. Runs last (via
 * `dependsOn`) and inspects emitted file paths to decide what to
 * re-export, so the barrel stays correct regardless of which plugins
 * are enabled.
 */
export const indexBarrel = definePluginConfig<
  "index",
  IndexBarrelConfig,
  IndexBarrelResolvedConfig,
  unknown
>({
  name: "index",
  defaultConfig,
  dependsOn: ["typescript", "events", "event-map", "dispatch", "amqplib"],
  handler(plugin) {
    const has = (base: string) =>
      plugin.files.some((f) => f.path === `${base}.gen.ts`);

    const statements: ts.Statement[] = [];

    if (has("amqp")) {
      statements.push(
        exportFromBarrel(
          [
            { name: "assertExchanges" },
            { name: "bindAndConsume" },
            { name: "publish" },
          ],
          "./amqp.gen",
        ),
      );
    }
    if (has("dispatch")) {
      statements.push(
        exportFromBarrel(
          [{ name: "Registry" }, { name: "createRegistry" }],
          "./dispatch.gen",
        ),
      );
    }
    if (has("event-map")) {
      statements.push(
        exportFromBarrel(
          [
            { name: "AnyMessage", isType: true },
            { name: "EventMap", isType: true },
            { name: "isMessageOfType" },
          ],
          "./event-map.gen",
        ),
      );
    }
    if (has("events")) {
      statements.push(
        exportFromBarrel(
          [{ name: "EventName", isType: true }, { name: "Events" }],
          "./events.gen",
        ),
      );
    }
    if (has("handlers")) {
      statements.push(
        exportFromBarrel([{ name: "handlers" }], "./handlers.gen"),
      );
    }
    if (has("types")) {
      statements.push(exportTypeStarFrom("./types.gen"));
    }

    plugin.emitTs("index.gen.ts", statements, { header: HEADER });
  },
});
