import type { MessageInterface } from "@asyncapi/parser";
import ts from "typescript";

import { exportInterface, tn } from "../../ast/ts-build.js";
import { definePluginConfig } from "../../plugin.js";

import { defaultConfig } from "./config.js";
import type { EventMapPluginConfig, EventMapResolvedConfig } from "./types.js";

const HEADER =
  "// AUTO-GENERATED by @ir-kit/asyncapi-typescript — do not hand-edit.";

const f = ts.factory;

export const eventMap = definePluginConfig<
  "event-map",
  EventMapPluginConfig,
  EventMapResolvedConfig,
  unknown
>({
  name: "event-map",
  defaultConfig,
  dependsOn: ["typescript"],
  handler(plugin) {
    const eventMapMembers: ts.TypeElement[] = [];
    const importNames = new Set<string>();

    for (const ev of plugin.forEach("message")) {
      if (ev.type !== "message") continue;
      const interfaceName = `${ev.message.id()}${plugin.config.messageSuffix}`;
      importNames.add(interfaceName);
      eventMapMembers.push(
        tn.property(inferEventType(ev.message), tn.ref(interfaceName)),
      );
    }

    const anyMessageAlias = f.createTypeAliasDeclaration(
      [f.createModifier(ts.SyntaxKind.ExportKeyword)],
      "AnyMessage",
      undefined,
      f.createIndexedAccessTypeNode(
        tn.ref("EventMap"),
        tn.keyOf(tn.ref("EventMap")),
      ),
    );

    plugin.emitTs(
      "event-map.gen.ts",
      [
        exportInterface("EventMap", eventMapMembers),
        anyMessageAlias,
        buildIsMessageOfType(),
      ],
      {
        header: HEADER,
        imports: [
          {
            from: "types.gen",
            isType: true,
            names: Array.from(importNames)
              .sort()
              .map((name) => ({ name })),
          },
        ],
      },
    );
  },
});

/** `export function isMessageOfType<K extends keyof EventMap>(msg, type): msg is EventMap[K]` */
function buildIsMessageOfType(): ts.FunctionDeclaration {
  return f.createFunctionDeclaration(
    [f.createModifier(ts.SyntaxKind.ExportKeyword)],
    undefined,
    "isMessageOfType",
    [
      f.createTypeParameterDeclaration(
        undefined,
        "K",
        tn.keyOf(tn.ref("EventMap")),
      ),
    ],
    [
      f.createParameterDeclaration(
        undefined,
        undefined,
        "msg",
        undefined,
        tn.ref("AnyMessage"),
      ),
      f.createParameterDeclaration(
        undefined,
        undefined,
        "type",
        undefined,
        tn.ref("K"),
      ),
    ],
    f.createTypePredicateNode(
      undefined,
      "msg",
      f.createIndexedAccessTypeNode(tn.ref("EventMap"), tn.ref("K")),
    ),
    f.createBlock(
      [
        f.createReturnStatement(
          f.createBinaryExpression(
            f.createPropertyAccessExpression(
              f.createParenthesizedExpression(
                f.createAsExpression(
                  f.createIdentifier("msg"),
                  f.createTypeLiteralNode([
                    tn.property("type", tn.string(), true),
                  ]),
                ),
              ),
              "type",
            ),
            f.createToken(ts.SyntaxKind.EqualsEqualsEqualsToken),
            f.createIdentifier("type"),
          ),
        ),
      ],
      true,
    ),
  );
}

function inferEventType(message: MessageInterface): string {
  const title = message.title?.();
  if (title) return title;
  const name = message.name?.();
  if (name) return name;
  return message.id();
}
