packages:
  - "packages/shared/*"
  - "packages/openapi/*"
  - "packages/openapi/plugins/*"
  - "packages/asyncapi/*"
  - "packages/fn-schema/*"
  - "packages/k6/*"
  - "apps/*"
  - "examples/*"
  - "tooling/*"
  - "!tooling/template/**"

catalog:
  "@asyncapi/modelina": "^5.0.0"
  "@asyncapi/parser": "^3.6.0"
  "@hey-api/codegen-core": "^0.8.1"
  "@hey-api/json-schema-ref-parser": "^1.4.1"
  "@hey-api/openapi-ts": "^0.97.0"
  "@hey-api/shared": "^0.4.2"
  "@hey-api/spec-types": "^0.2.0"
  "@types/node": "^22"
  "@clack/prompts": "^1.3.0"
  c12: "^3.3.4"
  chokidar: "^4.0.3"
  citty: "^0.2.2"
  consola: "^3.4.2"
  esbuild: "^0.27.7"
  tinyglobby: "^0.2.10"
  tsdown: "^0.22.0"
  typescript: "5.9.3"
  vitest: "^4.0.0"

patchedDependencies:
  "@ryoppippi/unplugin-typia": patches/@ryoppippi__unplugin-typia.patch
