packages:
  - "packages/shared/*"
  - "packages/openapi/*"
  - "packages/openapi/plugins/*"
  - "packages/asyncapi/*"
  - "packages/fn-schema/*"
  - "packages/k6/*"
  - "apps/*"
  - "examples/*"
  - "tooling/*"

catalog:
  "@asyncapi/modelina": "^5.0.0"
  "@asyncapi/parser": "^3.6.0"
  "@hey-api/codegen-core": "^0.8.1"
  "@hey-api/json-schema-ref-parser": "^1.4.1"
  "@hey-api/openapi-ts": "^0.97.0"
  "@hey-api/shared": "^0.4.2"
  "@hey-api/spec-types": "^0.2.0"
  "@types/node": "^22"
  vitest: "^4.0.0"

patchedDependencies:
  "@ryoppippi/unplugin-typia": patches/@ryoppippi__unplugin-typia.patch
