import type { MessageInterface } from "@asyncapi/parser";
import {
  getAmqpChannelBinding,
  getAmqpExchange,
} from "@ir-kit/asyncapi-core/bindings";
import { camel } from "@ir-kit/codegen-core";

import {
  asConst,
  exportConst,
  exportTypeAlias,
  lit,
  obj,
  tn,
} from "../../ast/ts-build.js";
import { definePluginConfig } from "../../plugin.js";

import { defaultConfig } from "./config.js";
import type { EventsPluginConfig, EventsResolvedConfig } from "./types.js";

const HEADER =
  "// AUTO-GENERATED by @ir-kit/asyncapi-typescript — do not hand-edit.";

export const events = definePluginConfig<
  "events",
  EventsPluginConfig,
  EventsResolvedConfig,
  unknown
>({
  name: "events",
  defaultConfig,
  handler(plugin) {
    const entries: Record<string, ReturnType<typeof obj>> = {};

    for (const ev of plugin.forEach("channel")) {
      if (ev.type !== "channel") continue;
      const channel = ev.channel;
      if (!getAmqpChannelBinding(channel)) continue;
      const exchange = getAmqpExchange(channel);
      if (!exchange) continue;

      for (const message of channel.messages().all()) {
        const eventType = inferEventType(message);
        const propertyName = camel(message.id());

        entries[propertyName] = obj({
          type: lit.string(eventType),
          routingKey: lit.string(channel.address() ?? eventType),
          exchange: lit.string(exchange.name),
          exchangeType: lit.string(exchange.type),
          contentType: lit.string(message.contentType() ?? "application/json"),
        });
      }
    }

    plugin.emitTs(
      plugin.config.fileName,
      [
        exportConst("Events", asConst(obj(entries))),
        exportTypeAlias("EventName", tn.keyOf(tn.typeOf("Events"))),
      ],
      { header: HEADER },
    );
  },
});

function inferEventType(message: MessageInterface): string {
  const title = message.title?.();
  if (title) return title;
  const name = message.name?.();
  if (name) return name;
  return message.id();
}
