import type { TsDsl } from "@hey-api/openapi-ts";
import ts from "typescript";

const printer = ts.createPrinter({
  newLine: ts.NewLineKind.LineFeed,
  removeComments: false,
});

/** Render a set of TS AST statements into a source-file string. */
export function printStatements(
  statements: ReadonlyArray<ts.Statement>,
  header?: string,
): string {
  const source = ts.createSourceFile(
    "out.ts",
    "",
    ts.ScriptTarget.ES2022,
    /* setParentNodes */ false,
    ts.ScriptKind.TS,
  );
  const body = statements
    .map((stmt) => printer.printNode(ts.EmitHint.Unspecified, stmt, source))
    .join("\n\n");
  return header ? `${header}\n\n${body}\n` : `${body}\n`;
}

/** Render DSL nodes by unwrapping each to its TS AST then printing. */
export function printDslNodes(
  nodes: ReadonlyArray<TsDsl<ts.Node>>,
  header?: string,
): string {
  return printStatements(
    nodes.map((n) => n.toAst() as ts.Statement),
    header,
  );
}

export const GENERATED_HEADER =
  "// AUTO-GENERATED by @ir-kit/k6-gen — do not edit by hand.";
