import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import ts from "typescript";

import { exportConst, tn } from "../../ast/ts-build.js";
import { definePluginConfig } from "../../plugin.js";
import { readBundle } from "../../runtime/copy-bundle.js";

import { defaultConfig } from "./config.js";
import type { DispatchPluginConfig, DispatchResolvedConfig } from "./types.js";

const bundleDir = resolve(dirname(fileURLToPath(import.meta.url)), "bundle");

const HEADER =
  "// AUTO-GENERATED by @ir-kit/asyncapi-typescript — do not hand-edit.";

const f = ts.factory;

/**
 * Emit the Registry runtime + spec-bound `handlers()` factory.
 *
 * - `dispatch.gen.ts` is pure-static (no spec references) → copied verbatim
 *   from `bundle/`.
 * - `handlers.gen.ts` mixes static (`createRegistry`, `RegistryOptions`)
 *   with spec-derived references (`Events`, `EventMap`) → built via
 *   `ts.factory` so the import graph is real, not text-templated.
 */
export const dispatch = definePluginConfig<
  "dispatch",
  DispatchPluginConfig,
  DispatchResolvedConfig,
  unknown
>({
  name: "dispatch",
  defaultConfig,
  dependsOn: ["events", "event-map"],
  async handler(plugin) {
    for (const file of await readBundle(bundleDir)) {
      plugin.emit(file);
    }

    plugin.emitTs(
      "handlers.gen.ts",
      [exportConst("handlers", buildHandlersFactory())],
      {
        header: HEADER,
        imports: [
          {
            from: "dispatch.gen",
            names: [
              { name: "createRegistry" },
              { name: "RegistryOptions", isType: true },
            ],
          },
          {
            from: "event-map.gen",
            isType: true,
            names: [{ name: "EventMap" }],
          },
          { from: "events.gen", names: [{ name: "Events" }] },
        ],
      },
    );
  },
});

/** `(opts?: RegistryOptions) => createRegistry<EventMap>(Events, opts)` */
function buildHandlersFactory(): ts.ArrowFunction {
  return f.createArrowFunction(
    undefined,
    undefined,
    [
      f.createParameterDeclaration(
        undefined,
        undefined,
        "opts",
        f.createToken(ts.SyntaxKind.QuestionToken),
        tn.ref("RegistryOptions"),
      ),
    ],
    undefined,
    undefined,
    f.createCallExpression(
      f.createIdentifier("createRegistry"),
      [tn.ref("EventMap")],
      [f.createIdentifier("Events"), f.createIdentifier("opts")],
    ),
  );
}
