import { TypeScriptGenerator } from "@asyncapi/modelina";

import { definePluginConfig } from "../../plugin.js";

import { defaultConfig } from "./config.js";
import type {
  TypescriptPluginConfig,
  TypescriptResolvedConfig,
} from "./types.js";

const HEADER = [
  "// AUTO-GENERATED by @ir-kit/asyncapi-typescript — do not hand-edit.",
  "",
  "",
].join("\n");

/**
 * Emit one TS interface per message payload schema declared in the spec.
 *
 * Each message's payload is fed to Modelina as a standalone JSON Schema
 * with `title = "<MessageId><suffix>"` injected so the top-level
 * interface is named after the spec's message id. Inner objects
 * referenced via $ref take their name from `components.schemas` (we
 * inject titles there too — parser dereferences $refs by the time we
 * read `payload.json()`, so the title is the only handle Modelina has).
 */
export const typescript = definePluginConfig<
  "typescript",
  TypescriptPluginConfig,
  TypescriptResolvedConfig,
  unknown
>({
  name: "typescript",
  defaultConfig,
  async handler(plugin) {
    const generator = new TypeScriptGenerator({
      modelType: "interface",
      processorOptions: {
        interpreter: { ignoreAdditionalProperties: true },
      },
      rawPropertyNames: true,
    });

    for (const schema of plugin.document.components()?.schemas()?.all() ?? []) {
      const id = schema.id();
      const raw = schema.json();
      if (id && typeof raw === "object" && raw !== null && !("title" in raw)) {
        (raw as Record<string, unknown>).title = id;
      }
    }

    const seen = new Map<string, string>();

    for (const ev of plugin.forEach("message")) {
      if (ev.type !== "message") continue;
      const payload = ev.message.payload();
      if (!payload) continue;

      const schema = JSON.parse(JSON.stringify(payload.json())) as Record<
        string,
        unknown
      >;
      schema.title = `${ev.message.id()}${plugin.config.messageSuffix}`;
      schema.$schema = "http://json-schema.org/draft-07/schema#";

      const models = await generator.generate(schema);
      for (const model of models) {
        if (!seen.has(model.modelName)) {
          seen.set(model.modelName, model.result);
        }
      }
    }

    const blocks = Array.from(seen.values())
      .filter((b) => b.trim().length > 0)
      .map(prefixExports);

    plugin.emit({
      path: "types.gen.ts",
      content: HEADER + blocks.join("\n\n") + "\n",
    });
  },
});

/** Modelina emits unexported decls; add `export` to top-level interface/type/enum. */
function prefixExports(block: string): string {
  return block.replace(
    /^(\s*)(interface|type|enum)\s/gm,
    (_, indent, kw) => `${indent}export ${kw} `,
  );
}
