// swift-tools-version:5.9
// Generated by openapi-swift. Re-emitted on every codegen run.

import PackageDescription

let package = Package(
    name: "PetstoreSDK",
    platforms: [.iOS(.v15), .macOS(.v13)],
    products: [
        .library(name: "PetstoreSDK", targets: ["PetstoreSDK"]),
    ],
    targets: [
        .target(
            name: "PetstoreSDK",
            path: ".",
            exclude: ["Package.swift"],
            sources: ["API", "Models"]
        ),
    ]
)
